# Generated by Django 3.1.7 on 2021-04-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210409_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeorder',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
